server:
  port: 8000
spring:
  application:
    name: crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    alipay-public-key: ${alipay.publicKey}
    app-id: ${alipay.id}
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: ${alipay.privateKey}
    notify-url: http://server.natappfree.cc/pay/notify
    return-url: http://www.zh.test.com/pay/return
    sign-type: RSA2